title: Joe and Huong Web
description: Miscellaneous personal stuff
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://www.joenhuong.com

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template



include:
  - CNAME # Some sites require this; see: https://github.com/criptowiki/criptowiki/issues/15#issuecomment-886890153

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - .jekyll-metadata
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md
 # theme test code
   - fixtures/
